{{- if and .Values.fileserver.enabled .Values.fileserver.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "vista3d.fullname" . }}-fileserver
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.fileserver.istio.host | quote }}
  gateways:
    - {{ .Values.fileserver.istio.gateway }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "vista3d.fullname" . }}-image-server.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.fileserver.port }}
{{- end }}
