apiVersion: v1
kind: Service
metadata:
  name: {{ include "vista3d.fullname" . }}-frontend
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
spec:
  selector:
    app: vista3d-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
