{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "vista3d.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      nodeSelector:
        {{- toYaml .Values.backend.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: NGC_API_KEY
              value: {{ .Values.backend.ngcApiKey | quote }}
            - name: ACCEPT_EULA
              value: "Y"
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.backend.volumeMounts | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
{{- end }}